extends SceneTree
const Policy = preload("../scripts/curiosity_policy.gd")
var passed := 0
var failed := 0
func check(value: bool, label: String) -> void:
	if value: passed+=1
	else: failed+=1
	print("%s %s" % ["PASS" if value else "FAIL",label])
func candidate(id: String, point: Vector2) -> Dictionary:
	return {"id":id,"point":point,"kind":"surface","confidence":0.7}
func _initialize() -> void:
	var p = Policy.new()
	var c := [candidate("a",Vector2(200,0)),candidate("b",Vector2(-200,0)),candidate("c",Vector2(0,400))]
	var first: Dictionary = p.choose(c,Vector2.ZERO,0)
	check(not str(first.target_id).is_empty(),"Unvisited reachable space creates exploration purpose")
	check(first.reason=="explore_unvisited","Novelty reason is inspectable")
	check(p.choose(c,Vector2.ZERO,0).target_id==first.target_id,"No frame random walk in tie-breaking")
	var reversed := c.duplicate(); reversed.reverse()
	check(p.choose(reversed,Vector2.ZERO,0).target_id==first.target_id,"Candidate order cannot change ties")
	check(p.choose([candidate("near",Vector2(3,0))],Vector2.ZERO,0).target_id=="","Near-zero movement rests")
	p.observe_arrival("a",Vector2(200,0),1,"arrived")
	check(p.choose(c,Vector2(200,0),5).reason=="settling_after_arrival","Arrival creates bounded rest")
	check(p.choose([candidate("a",Vector2(200,0))],Vector2.ZERO,20).target_id=="","Recently visited target not immediately repeated")
	p.observe_arrival("b",Vector2(-200,0),30,"arrived")
	check(p.choose([candidate("a",Vector2(200,0))],Vector2(-200,0),50).target_id=="","Immediate A-B-A shuttle suppressed")
	check(p.choose([candidate("a",Vector2(200,0))],Vector2(-200,0),200).target_id=="a","Habituation recovers instead of permanently blacklisting")
	p.reset()
	p.choose(c,Vector2.ZERO,0)
	p.observe_arrival("a",Vector2(200,0),1,"unreachable")
	check(p.choose([c[0]],Vector2.ZERO,30).target_id=="","Failed target cooldown")
	check(p.choose([c[0]],Vector2.ZERO,62).target_id=="a","Failure cooldown expires")
	p.observe_arrival("a",Vector2(200,0),63,"failed")
	check(p.choose([c[0]],Vector2.ZERO,130).target_id=="","Repeated failure increases retry delay")
	p.reset()
	p.observe_arrival("a",Vector2(200,0),1,"cancelled")
	check(p.choose([c[0]],Vector2.ZERO,2).target_id=="a","User interruption does not mark destination unreachable")
	p.reset()
	p.choose(c,Vector2.ZERO,0)
	p.observe_arrival("old-id",Vector2(200,0),1,"arrived")
	var memory_choice: Dictionary = p.choose([candidate("renamed",Vector2(210,0)),candidate("fresh",Vector2(-210,0))],Vector2.ZERO,20)
	check(memory_choice.target_id=="fresh","Spatial habituation survives target ID change")
	p.reset()
	p.choose(c,Vector2.ZERO,0)
	p.observe_arrival("old",Vector2(200,0),0,"arrived")
	p.observe_arrival("old",Vector2(200,0),1,"arrived")
	check(p.choose([candidate("new-id-same-place",Vector2(210,0))],Vector2.ZERO,14).reason=="low_interest","Low-value habituated area rests instead of compulsory travel")
	p.reset()
	var translated = Policy.new()
	var shift := Vector2(314.25,-923.5)
	var shifted: Array = []
	for row in c: shifted.append(candidate(row.id,row.point+shift))
	p.choose(c,Vector2.ZERO,0); translated.choose(shifted,shift,0)
	p.observe_arrival("a",Vector2(200,0),1,"arrived")
	translated.observe_arrival("a",Vector2(200,0)+shift,1,"arrived")
	var base: Dictionary = p.choose(c,Vector2.ZERO,110)
	var moved: Dictionary = translated.choose(shifted,shift,110)
	check(base.target_id==moved.target_id,"Translation-invariant memory rankings")
	var same: bool = base.scores.size()==moved.scores.size()
	for i in base.scores.size(): same = same and absf(float(base.scores[i].score)-float(moved.scores[i].score))<0.00001
	check(same,"Translation-invariant score magnitudes")
	p.reset()
	check(p.choose([candidate("far",Vector2(700,0)),candidate("near",Vector2(100,0))],Vector2.ZERO,0).target_id=="near","Equivalent novelty prefers modest travel cost")
	var cross := [candidate("right",Vector2(200,0)),candidate("down",Vector2(0,200))]
	check(p.choose(cross,Vector2.ZERO,0,{"heading":Vector2.RIGHT,"forward":1.0}).target_id=="right","External forward drive uses explicit heading geometry")
	check(p.choose(cross,Vector2.ZERO,0,{"heading":Vector2.RIGHT,"forward":1.0,"turn":1.0}).target_id=="down","External turn maps to documented signed 90-degree preference")
	var neutral: Dictionary = p.choose(cross,Vector2.ZERO,0)
	check(p.choose(cross,Vector2.ZERO,0,{"heading":"bad","turn":NAN}).target_id==neutral.target_id,"Malformed drive falls back to baseline")
	check(p.choose(c,Vector2.INF,0).reason=="invalid_context","Invalid position cannot produce movement")
	for i in 200: p.observe_arrival("id%d"%i,Vector2(i*160,0),float(i+1),"arrived")
	check(p._memory.size()<=128,"Combined target/spatial memory stays within128")
	check(p._arrivals.size()<=2,"Arrival sequence memory is bounded")
	p.reset()
	check(p._memory.is_empty() and p._arrivals.is_empty(),"Character reset clears spatial history")
	var sensing = Policy.new()
	var bilateral: Dictionary = sensing.sensory([candidate("left",Vector2(-200,0))],Vector2.ZERO,0)
	check(float(bilateral.left)>0.0 and is_zero_approx(float(bilateral.right)),"Sensory novelty follows explicit screen-left axis")
	check(sensing._memory.is_empty() and not sensing._origin.is_finite() and sensing._time==-INF,"Sensory read never commits visit/time/origin")
	sensing.choose(c,Vector2.ZERO,0)
	var fresh: Dictionary = sensing.sensory([c[0]],Vector2.ZERO,1)
	sensing.observe_arrival("a",Vector2(200,0),1,"arrived")
	var familiar: Dictionary = sensing.sensory([c[0]],Vector2.ZERO,2)
	check(float(familiar.right)<float(fresh.right),"External sensory inputs reuse actual visit habituation")
	sensing.observe_arrival("b",Vector2(-200,0),3,"failed")
	check(is_zero_approx(float(sensing.sensory([c[1]],Vector2.ZERO,4).left)),"Failed target contributes no current sensory drive")
	check(sensing.sensory([],Vector2.ZERO,4).candidate_count==0,"No fabricated stimulus without candidates")
	var relocating = Policy.new()
	relocating.choose(c,Vector2.ZERO,0)
	relocating.observe_arrival("support:left",Vector2(200,0),1,"arrived")
	var moved_target := candidate("support:left",Vector2(-300,0))
	var relocated: Dictionary = relocating.choose([moved_target],Vector2.ZERO,20)
	check(relocated.target_id=="support:left" and relocated.reason=="explore_unvisited","Reused ID at a new place regains novelty and avoids old arrival suppression")
	check(float(relocating.sensory([moved_target],Vector2.ZERO,20).left)>float(relocating.sensory([candidate("support:left",Vector2(200,0))],Vector2.ZERO,20).right),"Sensory ignores stale target familiarity after relocation")
	relocating.observe_arrival("support:right",Vector2(300,0),21,"failed")
	check(relocating.choose([candidate("support:right",Vector2(-400,0))],Vector2.ZERO,22).target_id=="support:right","Relocated destination does not inherit old failure cooldown")
	check(relocating.choose([candidate("support:right",Vector2(305,0))],Vector2.ZERO,22).target_id=="","Small target jitter preserves failure cooldown")
	var old_place: Dictionary = relocating.choose([candidate("different-id",Vector2(200,0))],Vector2.ZERO,22)
	check(float(old_place.scores[0].novelty)<0.5,"Relocation leaves spatial familiarity at original place")
	print("Curiosity policy: %d passed, %d failed" % [passed,failed])
	quit(1 if failed else 0)
