extends SceneTree
const Preferences = preload("../scripts/placement_preferences.gd")
var passed := 0
var failed := 0
func check(value: bool, label: String) -> void:
	if value: passed+=1
	else: failed+=1
	print("%s %s" % ["PASS" if value else "FAIL",label])
func _initialize() -> void:
	var p = Preferences.new()
	p.configure("")
	var monitor := Rect2(0,0,1000,800)
	var point := Vector2(250,200)
	check(p.bonus("a",point,monitor,"window",100)==0,"No preference invented before explicit placements")
	check(p.record_placement("a",point,monitor,"window",100),"Explicit placement accepted")
	var once: float = p.bonus("a",point,monitor,"window",100)
	check(once>0 and once<=0.25,"One placement learns bounded positive preference")
	check(p.bonus("a",Vector2(950,750),monitor,"window",100)<once,"Preference is spatially localized")
	check(p.bonus("b",point,monitor,"window",100)==0,"Characters retain independent preferences")
	check(p.bonus("a",point,monitor,"floor",100)<once,"Surface context distinguishes nearby placements")
	check(p.bonus("a",point,monitor,"window",100+Preferences.HALF_LIFE_SECONDS)<once,"Old evidence decays with time")
	p.record_placement("a",point,monitor,"window",100)
	check(p.bonus("a",point,monitor,"window",100)>once,"Repeated explicit placements update learning online")
	var transformed := Rect2(-600,300,2000,1600)
	check(is_equal_approx(p.bonus("a",Vector2(-100,700),transformed,"window",100),p.bonus("a",point,monitor,"window",100)),"Monitor translation/resizing preserve normalized preference")
	var before: Dictionary = p.export_diagnostics()
	for i in 20: p.bonus("a",point,monitor,"window",float(100+i))
	check(p.export_diagnostics()==before,"Scoring is read-only; autonomous choices never reinforce")
	var replay = Preferences.new();replay.configure("")
	check(replay.rebuild(before.events),"Offline replay accepts normalized explicit history")
	check(replay.bonus("a",point,monitor,"window",150)==p.bonus("a",point,monitor,"window",150),"Offline rebuild exactly matches online model")
	check(not p.record_placement("a",Vector2.INF,monitor,"window",100),"Invalid placement rejected")
	check(not p.record_placement("a",Vector2(1200,200),monitor,"window",100),"Off-monitor position is not silently clamped into evidence")
	check(not p.rebuild([{"character":"a"}]) and p.export_diagnostics()==before,"Invalid rebuild leaves existing model intact")
	for i in 300: p.record_placement("a",point,monitor,"window",float(200+i))
	check(p.export_diagnostics().event_count==256,"Event log is bounded")
	check(p.bonus("a",point,monitor,"window",600)<=0.25,"Repeated evidence cannot exceed max bonus")
	for i in 20: p.record_placement("character%d"%i,point,monitor,"window",float(1000+i))
	check(p.export_diagnostics().characters.size()<=16,"Character state is bounded")
	var capped: Dictionary = p.export_diagnostics()
	replay.rebuild(capped.events)
	check(replay.bonus("character19",point,monitor,"window",1100)==p.bonus("character19",point,monitor,"window",1100),"Bounded persisted history rebuild is exact")
	var path := "user://placement-probe-%d.json" % OS.get_process_id()
	var saved = Preferences.new()
	check(saved.configure(path),"Fresh persistent model configured")
	check(saved.record_placement("a",point,monitor,"taskbar",100),"First event atomically persists")
	check(saved.record_placement("a",point,monitor,"taskbar",101),"Replacing existing document persists atomically")
	var loaded = Preferences.new()
	check(loaded.configure(path),"Persisted document validates and reloads")
	check(loaded.bonus("a",point,monitor,"taskbar",120)==saved.bonus("a",point,monitor,"taskbar",120),"Reload reproduces learned preference")
	check(not FileAccess.file_exists(path+".tmp"),"No partial temporary document remains")
	check(loaded.reset("a") and loaded.bonus("a",point,monitor,"taskbar",120)==0,"Explicit per-character reset removes preference")
	var malformed := FileAccess.open(path,FileAccess.WRITE);malformed.store_string('{"version":1,"events":[{"x":2}]}');malformed.close()
	check(not loaded.configure(path) and loaded.export_diagnostics().event_count==0,"Malformed persisted JSON fails closed")
	DirAccess.remove_absolute(path)
	print("Placement preferences: %d passed, %d failed" % [passed,failed])
	quit(1 if failed else 0)
